"""initial_schema

Revision ID: 64c7a8b65f57
Revises: 
Create Date: 2026-09-04 19:03:11.828741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c7a8b65f57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('root_ioc_value', sa.String(length=1024), nullable=False),
    sa.Column('root_ioc_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('pivot_depth', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_root_ioc_value'), 'investigations', ['root_ioc_value'], unique=False)
    op.create_table('investigation_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_events_investigation_id'), 'investigation_events', ['investigation_id'], unique=False)
    op.create_table('iocs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_value', sa.String(length=1024), nullable=False),
    sa.Column('ioc_type', sa.String(length=32), nullable=False),
    sa.Column('is_root', sa.Boolean(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.String(length=64), nullable=True),
    sa.Column('last_seen', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ioc_investigation_canon_type', 'iocs', ['investigation_id', 'canonical_value', 'ioc_type'], unique=False)
    op.create_index(op.f('ix_iocs_canonical_value'), 'iocs', ['canonical_value'], unique=False)
    op.create_index(op.f('ix_iocs_investigation_id'), 'iocs', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_iocs_ioc_type'), 'iocs', ['ioc_type'], unique=False)
    op.create_table('pivot_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('parent_ioc', sa.String(length=1024), nullable=False),
    sa.Column('child_ioc', sa.String(length=1024), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pivot_runs_investigation_id'), 'pivot_runs', ['investigation_id'], unique=False)
    op.create_table('provider_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('ioc_value', sa.String(length=1024), nullable=False),
    sa.Column('ioc_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('malicious_count', sa.Integer(), nullable=True),
    sa.Column('suspicious_count', sa.Integer(), nullable=True),
    sa.Column('harmless_count', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('threat_actors', sa.JSON(), nullable=True),
    sa.Column('malware_families', sa.JSON(), nullable=True),
    sa.Column('infrastructure_data', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_results_investigation_id'), 'provider_results', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_provider_results_provider_name'), 'provider_results', ['provider_name'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('source_value', sa.String(length=1024), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('target_value', sa.String(length=1024), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('providers', sa.JSON(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=True),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rel_src_tgt_type', 'relationships', ['investigation_id', 'source_value', 'target_value', 'relationship_type'], unique=False)
    op.create_index(op.f('ix_relationships_investigation_id'), 'relationships', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_relationships_relationship_type'), 'relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_relationships_source_value'), 'relationships', ['source_value'], unique=False)
    op.create_index(op.f('ix_relationships_target_value'), 'relationships', ['target_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_target_value'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_value'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_relationship_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_investigation_id'), table_name='relationships')
    op.drop_index('idx_rel_src_tgt_type', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_provider_results_provider_name'), table_name='provider_results')
    op.drop_index(op.f('ix_provider_results_investigation_id'), table_name='provider_results')
    op.drop_table('provider_results')
    op.drop_index(op.f('ix_pivot_runs_investigation_id'), table_name='pivot_runs')
    op.drop_table('pivot_runs')
    op.drop_index(op.f('ix_iocs_ioc_type'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_investigation_id'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_canonical_value'), table_name='iocs')
    op.drop_index('idx_ioc_investigation_canon_type', table_name='iocs')
    op.drop_table('iocs')
    op.drop_index(op.f('ix_investigation_events_investigation_id'), table_name='investigation_events')
    op.drop_table('investigation_events')
    op.drop_index(op.f('ix_investigations_root_ioc_value'), table_name='investigations')
    op.drop_table('investigations')
    # ### end Alembic commands ###
